<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\dashboard-icon.png" />
    <None Remove="Resources\Images\logout-icon.png" />
    <None Remove="Resources\Images\menu-icon.png" />
    <None Remove="Resources\Images\notification-icon.png" />
    <None Remove="Resources\Images\register-icon.png" />
    <None Remove="Resources\Images\teacher-icon.png" />
    <None Remove="Resources\Images\tuitionFee-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BLL\BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\classroom-icon.png" />
    <Resource Include="Resources\Images\course-icon.png" />
    <Resource Include="Resources\Images\dashboard-icon.png" />
    <Resource Include="Resources\Images\logout-icon.png" />
    <Resource Include="Resources\Images\register-icon.png" />
    <Resource Include="Resources\Images\student-icon.png" />
    <Resource Include="Resources\Images\menu-icon.png" />
    <Resource Include="Resources\Images\notification-icon.png" />
    <Resource Include="Resources\Images\teacher-icon.png" />
    <Resource Include="Resources\Images\tuitionFee-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
